import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { createServer, type IncomingMessage } from "node:http";
import type { AddressInfo } from "node:net";
import { inspect } from "node:util";

import { secp256k1 } from "@noble/curves/secp256k1.js";
import { keccak_256 } from "@noble/hashes/sha3.js";

import {
  AgentSigner,
  agentCanonicalString,
  type AgentAuthHeaders,
} from "../src/agent.js";
import { Client, customNetwork } from "../src/client.js";
import { MissingCredentialsError, NexusExchangeError } from "../src/errors.js";

// The spec's known-answer vectors, copied verbatim from the `agentAuth`
// security scheme's `x-nexus-test-vectors` in nexus-xyz/nexus#12162
// (`eng/apps/exchange/api/openapi.json`). They are the same three vectors the
// Rust SDK pins (nexus-exchange-rs#156, `src/auth/agent.rs`), generated by the
// exchange terminal's own signer and reproduced independently with Python
// `eth-account`. Together they cover an empty-body GET, a JSON POST with a
// lower-case method, a DELETE with a query, and both values of `v`.
//
// When the pinned spec (spec/openapi.json) reaches a release that carries
// `agentAuth`, these should be read from the vendored spec instead.
const VECTORS = [
  {
    private_key:
      "0x0101010101010101010101010101010101010101010101010101010101010101",
    method: "GET",
    path: "/account/summary",
    query: "",
    body: "",
    "x-timestamp": "1776033900000",
    "x-nonce": "1776033900000",
    canonical_string:
      "GET\n/account/summary\n\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n1776033900000\n1776033900000",
    digest:
      "0xe3e5ce99d3adbeeb18ab49b7e7b24b135689fc4912c9664f40bc4a3f1dfbc6a3",
    "x-agent": "0x1a642f0e3c3af545e7acbd38b07251b3990914f1",
    "x-signature":
      "0xd94b40dff9c3d0e0a649178b6eb3159d9a3522a1ccc66390b42a7a444b8e52c85f2d2a9d66e8a48ac5040d8e96f526d352b3b7a686634280b9192eb6c12a61b61b",
  },
  {
    private_key:
      "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318",
    method: "post",
    path: "/orders",
    query: "",
    body: '{"market_id":"BTC-USDX-PERP","side":"Buy","order_type":"Limit","quantity":"0.1","price":"50000"}',
    "x-timestamp": "1776033900123",
    "x-nonce": "42",
    canonical_string:
      "POST\n/orders\n\n59ddf9017ca0eb5f8802afd1a2d1584b2d93b0260a0fcd62a1b94b3ff92b332c\n1776033900123\n42",
    digest:
      "0xe27ade6101c417d2c393abfce8f35b6e1551cf0ce5c50dfbe12f8d6f399ffc35",
    "x-agent": "0x2c7536e3605d9c16a7a3d7b1898e529396a65c23",
    "x-signature":
      "0xeef09105834062da10d208be38311995d04cbc5e05043b89e7cbe6d4497d11b51f61729639551a8cfb6ea3e4fe0765afeba7bf3b5f5e09f63bc095c89005b61d1c",
  },
  {
    private_key:
      "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318",
    method: "DELETE",
    path: "/orders",
    query: "market_id=BTC-USDX-PERP",
    body: "",
    "x-timestamp": "1776033900456",
    "x-nonce": "43",
    canonical_string:
      "DELETE\n/orders\nmarket_id=BTC-USDX-PERP\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n1776033900456\n43",
    digest:
      "0x69159f66a03a9b6e3e3e4582ed8f497cdc47545641db9a010b4cb6efe1649fea",
    "x-agent": "0x2c7536e3605d9c16a7a3d7b1898e529396a65c23",
    "x-signature":
      "0x002554d4216daa303818dfcc5a15eb86940691e11ad6ab25a270916ec5a43a1a5eb4c18dd898aa3ebd099c1683337e3c545417c2b67a0d384f1d0355ffa807f91c",
  },
] as const;

const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const SECP256K1_N = secp256k1.Point.CURVE().n;

/**
 * Independent re-implementation of the server's check
 * (`exchange-sec-utils::signing::recover_secp256k1`): parse a 65-byte
 * `r||s||v` signature, refuse high-S, recover over the given digest, and return
 * the Ethereum address. Uses only @noble primitives, never src/agent.ts.
 */
function recoverAddress(digest: Uint8Array, signatureHex: string): string {
  assert.match(signatureHex, /^0x[0-9a-f]{130}$/);
  const sig = Buffer.from(signatureHex.slice(2), "hex");
  const v = sig[64];
  assert.ok(v === 27 || v === 28, `v must be 27 or 28, got ${v}`);
  const s = BigInt(`0x${hex(sig.subarray(32, 64))}`);
  assert.ok(s <= SECP256K1_N / 2n, "signature must be low-S");
  // noble's `recovered` format is recid(1) || r(32) || s(32).
  const recovered = new Uint8Array(65);
  recovered[0] = v - 27;
  recovered.set(sig.subarray(0, 64), 1);
  const pub = secp256k1.recoverPublicKey(recovered, digest, {
    prehash: false,
  });
  const uncompressed = secp256k1.Point.fromBytes(pub).toBytes(false);
  return `0x${hex(keccak_256(uncompressed.subarray(1)).subarray(12))}`;
}

// -- known-answer vectors ----------------------------------------------------

for (const v of VECTORS) {
  test(`spec vector: ${v.method} ${v.path}${v.query ? `?${v.query}` : ""}`, () => {
    const signer = AgentSigner.fromHex(v.private_key);
    assert.equal(signer.address, v["x-agent"]);

    const parts = {
      method: v.method,
      path: v.path,
      query: v.query,
      body: v.body,
      timestampMs: Number(v["x-timestamp"]),
      nonce: Number(v["x-nonce"]),
    };
    const canonical = agentCanonicalString(parts);
    assert.equal(canonical, v.canonical_string);
    assert.equal(
      `0x${hex(keccak_256(new TextEncoder().encode(canonical)))}`,
      v.digest,
    );

    // Byte-for-byte: the whole header set, nothing more and nothing less.
    assert.deepEqual(signer.sign(parts), {
      "x-agent": v["x-agent"],
      "x-timestamp": v["x-timestamp"],
      "x-nonce": v["x-nonce"],
      "x-signature": v["x-signature"],
    });
    // A body given as bytes signs identically to the same body as a string.
    assert.deepEqual(
      signer.sign({ ...parts, body: new TextEncoder().encode(v.body) }),
      signer.sign(parts),
    );
  });
}

test("spec vectors cover both recovery ids", () => {
  const vs = new Set(VECTORS.map((v) => v["x-signature"].slice(-2)));
  assert.deepEqual([...vs].sort(), ["1b", "1c"]);
});

// The server's own pinned vector (`exchange-sec-utils::signing`
// `canonical_string_matches_the_pinned_wire_format`).
test("canonical string matches the server's pinned wire format", () => {
  assert.equal(
    agentCanonicalString({
      method: "post",
      path: "/account/withdraw",
      query: "a=1",
      body: "hello",
      timestampMs: 1700,
      nonce: 42,
    }),
    "POST\n/account/withdraw\na=1\n" +
      "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\n1700\n42",
  );
});

// -- recovery ------------------------------------------------------------------

test("signature recovers to x-agent over the UNPREFIXED keccak256", () => {
  const signer = AgentSigner.fromHex(VECTORS[1].private_key);
  const parts = {
    method: "POST",
    path: "/api/v1/orders",
    query: "",
    body: "{}",
    timestampMs: 1_776_033_900_000,
    nonce: 7,
  };
  const headers = signer.sign(parts);
  const canonical = new TextEncoder().encode(agentCanonicalString(parts));

  assert.equal(
    recoverAddress(keccak_256(canonical), headers["x-signature"]),
    headers["x-agent"],
  );

  // An EIP-191 prefix must not creep into the prehash: under the prefixed
  // digest the same signature recovers to some other address.
  const prefix = new TextEncoder().encode(
    `\x19Ethereum Signed Message:\n${canonical.length}`,
  );
  const prefixed = keccak_256(Buffer.concat([prefix, canonical]));
  assert.notEqual(
    recoverAddress(prefixed, headers["x-signature"]),
    headers["x-agent"],
  );
});

test("every spec vector signature recovers to its x-agent", () => {
  for (const v of VECTORS) {
    const digest = Buffer.from(v.digest.slice(2), "hex");
    assert.equal(recoverAddress(digest, v["x-signature"]), v["x-agent"]);
  }
});

// -- nonces --------------------------------------------------------------------

test("nonce is max(last + 1, timestamp) and strictly increases", () => {
  const signer = AgentSigner.fromHex(VECTORS[0].private_key);
  const nonce = (ts: number) =>
    Number(
      signer.authHeaders({ method: "POST", path: "/orders", timestampMs: ts })[
        "x-nonce"
      ],
    );
  assert.equal(nonce(1_000), 1_000);
  // Two requests in the same millisecond still get distinct nonces.
  assert.equal(nonce(1_000), 1_001);
  // A clock that steps backwards does not regress the nonce.
  assert.equal(nonce(500), 1_002);
  // Once the clock moves past the counter, the nonce follows the clock.
  assert.equal(nonce(5_000), 5_000);
});

test("authHeaders stamps x-timestamp with the request time, not the nonce", () => {
  const signer = AgentSigner.fromHex(VECTORS[0].private_key);
  signer.nextNonce(10_000);
  const h = signer.authHeaders({
    method: "GET",
    path: "/a",
    timestampMs: 2_000,
  });
  assert.equal(h["x-timestamp"], "2000");
  assert.equal(h["x-nonce"], "10001");
});

test("sign() with an explicit nonce does not advance the signer", () => {
  const signer = AgentSigner.fromHex(VECTORS[0].private_key);
  signer.sign({ method: "POST", path: "/o", timestampMs: 1, nonce: 99_999 });
  assert.equal(signer.nextNonce(1), 1);
});

test("nonces are unique across interleaved async callers", async () => {
  const signer = AgentSigner.fromHex(VECTORS[0].private_key);
  const all = await Promise.all(
    Array.from({ length: 200 }, async (_, i) => {
      await new Promise((r) => setImmediate(r));
      return signer.nextNonce(i % 7);
    }),
  );
  assert.equal(new Set(all).size, all.length);
});

test("out-of-range timestamps and nonces are refused, not signed", () => {
  const signer = AgentSigner.fromHex(VECTORS[0].private_key);
  for (const bad of [-1, 1.5, Number.NaN, 2 ** 53]) {
    assert.throws(
      () =>
        signer.sign({ method: "GET", path: "/", timestampMs: bad, nonce: 1 }),
      NexusExchangeError,
    );
    assert.throws(
      () =>
        signer.sign({ method: "GET", path: "/", timestampMs: 1, nonce: bad }),
      NexusExchangeError,
    );
  }
});

// -- key handling ---------------------------------------------------------------

test("invalid keys are rejected without echoing them", () => {
  for (const bad of ["not-hex", "0x1234", "00".repeat(32)]) {
    assert.throws(
      () => AgentSigner.fromHex(bad),
      (err: unknown) =>
        err instanceof MissingCredentialsError &&
        !err.message.includes(bad.slice(0, 8)),
    );
  }
  // 0x-prefix optional.
  assert.equal(
    AgentSigner.fromHex(VECTORS[0].private_key.slice(2)).address,
    VECTORS[0]["x-agent"],
  );
});

test("the private key never renders", () => {
  const signer = AgentSigner.fromHex(VECTORS[0].private_key);
  const needle = "0101010101010101";
  for (const rendered of [
    String(signer),
    JSON.stringify(signer),
    inspect(signer, { showHidden: true, depth: 5 }),
  ]) {
    assert.ok(!rendered.includes(needle), rendered);
  }
});

// -- client wiring --------------------------------------------------------------

test("agentSigner and apiKey/apiSecret are mutually exclusive", () => {
  const agentSigner = AgentSigner.fromHex(VECTORS[1].private_key);
  assert.throws(
    () => new Client({ agentSigner, apiKey: "k", apiSecret: "ab" }),
    /either `agentSigner` or `apiKey`/,
  );
  assert.throws(
    () => new Client({ agentSigner, apiKey: "k" }),
    NexusExchangeError,
  );
  assert.equal(new Client({ agentSigner }).hasCredentials, true);
});

test("agent-management routes are refused locally for an agent-signed client", async () => {
  let sent = 0;
  const client = new Client({
    agentSigner: AgentSigner.fromHex(VECTORS[1].private_key),
    fetchImpl: (async () => {
      sent++;
      return new Response("[]");
    }) as unknown as typeof fetch,
  });
  await assert.rejects(client.listAgents(), MissingCredentialsError);
  await assert.rejects(client.revokeAgent("0xabc"), MissingCredentialsError);
  assert.equal(sent, 0, "nothing may be signed or sent");
});

interface Received {
  method: string;
  path: string;
  query: string;
  headers: IncomingMessage["headers"];
  body: Buffer;
}

/**
 * A real HTTP server that verifies agent auth the way the accounts service
 * does (`agent_verify::try_authenticate_agent`), independently of src/agent.ts:
 * ±30 s window, ecrecover over unprefixed keccak256(canonical) must equal
 * `x-agent`, and a strictly increasing nonce on mutating methods only.
 * Answers 401 on any failure, like the server.
 */
async function withAgentVerifier(
  nowMs: number,
  run: (baseUrl: string, received: Received[]) => Promise<void>,
): Promise<void> {
  const received: Received[] = [];
  const lastNonce = new Map<string, bigint>();
  const server = createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on("data", (c: Buffer) => chunks.push(c));
    req.on("end", () => {
      const body = Buffer.concat(chunks);
      const raw = req.url ?? "/";
      const q = raw.indexOf("?");
      const path = q === -1 ? raw : raw.slice(0, q);
      const query = q === -1 ? "" : raw.slice(q + 1);
      const method = req.method ?? "GET";
      received.push({ method, path, query, headers: req.headers, body });

      const agent = String(req.headers["x-agent"] ?? "");
      const ts = String(req.headers["x-timestamp"] ?? "");
      const nonce = String(req.headers["x-nonce"] ?? "");
      const sig = String(req.headers["x-signature"] ?? "");
      let ok = /^\d+$/.test(ts) && /^\d+$/.test(nonce);
      ok &&= Math.abs(Number(ts) - nowMs) <= 30_000;
      if (ok) {
        const canonical = [
          method.toUpperCase(),
          path,
          query,
          createHash("sha256").update(body).digest("hex"),
          ts,
          nonce,
        ].join("\n");
        try {
          ok =
            recoverAddress(keccak_256(Buffer.from(canonical)), sig) === agent;
        } catch {
          ok = false;
        }
      }
      if (ok && !["GET", "HEAD", "OPTIONS", "TRACE"].includes(method)) {
        const n = BigInt(nonce);
        ok = n > (lastNonce.get(agent) ?? -1n);
        if (ok) lastNonce.set(agent, n);
      }
      res.writeHead(ok ? 200 : 401, { "content-type": "application/json" });
      res.end(
        ok ? (method === "DELETE" ? "" : "{}") : '{"code":"UNAUTHORIZED"}',
      );
    });
  });
  await new Promise<void>((r) => server.listen(0, "127.0.0.1", r));
  const { port } = server.address() as AddressInfo;
  try {
    await run(`http://127.0.0.1:${port}`, received);
  } finally {
    await new Promise<void>((r) => server.close(() => r()));
  }
}

test("mock server: an agent-signed client sends exactly the agentAuth headers", async () => {
  const now = 1_776_033_900_123;
  const signer = AgentSigner.fromHex(VECTORS[1].private_key);
  await withAgentVerifier(now, async (baseUrl, received) => {
    const client = new Client({
      network: customNetwork({ label: "agent-mock", baseUrl, funds: "play" }),
      agentSigner: signer,
      nowMs: () => now,
      retry: { maxRetries: 0 },
    });

    await client.placeOrder({
      market_id: "BTC-USDX-PERP",
      side: "Buy",
      order_type: "Limit",
      quantity: "0.1",
      price: "50000",
      time_in_force: "GTC",
    });
    await client.getOrder("ord-1", "BTC-USDX-PERP"); // root route + query
    await client.cancelAllOrders();

    assert.equal(received.length, 3);
    const [post, get, del] = received;
    assert.equal(post.path, "/api/v1/orders");
    assert.equal(get.path, "/orders/ord-1");
    assert.equal(get.query, "market_id=BTC-USDX-PERP");
    assert.equal(del.method, "DELETE");

    for (const r of received) {
      // Exactly the four agent headers, and no HMAC or bearer credential.
      const authHeaders = Object.keys(r.headers)
        .filter((k) =>
          /^x-(agent|timestamp|nonce|signature|api-key)$|^authorization$/.test(
            k,
          ),
        )
        .sort();
      assert.deepEqual(authHeaders, [
        "x-agent",
        "x-nonce",
        "x-signature",
        "x-timestamp",
      ]);
      assert.equal(r.headers["x-agent"], VECTORS[1]["x-agent"]);
      assert.equal(r.headers["x-timestamp"], String(now));
    }
    // Nonces: the first is the timestamp, then strictly increasing.
    assert.deepEqual(
      received.map((r) => r.headers["x-nonce"]),
      [String(now), String(now + 1), String(now + 2)],
    );

    // The POST is byte-identical to what the signer produces for those exact
    // request bytes — i.e. the client signs the bytes it sends.
    assert.equal(
      post.headers["x-signature"],
      signer.sign({
        method: "POST",
        path: "/api/v1/orders",
        body: post.body,
        timestampMs: now,
        nonce: now,
      })["x-signature"],
    );
  });
});

test("mock server: a write whose nonce arrives out of order is refused (ENG-17010)", async () => {
  // Documents the caveat rather than fixing it: nonces are issued in order,
  // but if the higher one lands first the server rejects the lower one with
  // the same opaque 401 as a bad signature.
  const now = 1_776_033_900_000;
  const signer = AgentSigner.fromHex(VECTORS[1].private_key);
  const parts = { method: "DELETE", path: "/api/v1/orders", timestampMs: now };
  const first = signer.authHeaders(parts);
  const second = signer.authHeaders(parts);
  assert.ok(Number(second["x-nonce"]) > Number(first["x-nonce"]));

  await withAgentVerifier(now, async (baseUrl) => {
    const send = (h: AgentAuthHeaders) =>
      fetch(`${baseUrl}/api/v1/orders`, {
        method: "DELETE",
        headers: { ...h },
      });
    assert.equal((await send(second)).status, 200);
    assert.equal((await send(first)).status, 401);
  });
});

test("mock server: a stale timestamp is refused", async () => {
  const now = 1_776_033_900_000;
  await withAgentVerifier(now, async (baseUrl) => {
    const client = new Client({
      network: customNetwork({ label: "agent-mock", baseUrl, funds: "play" }),
      agentSigner: AgentSigner.fromHex(VECTORS[1].private_key),
      nowMs: () => now - 30_001,
      retry: { maxRetries: 0 },
    });
    await assert.rejects(client.getOpenOrders(), { status: 401 });
  });
});
